<%
' Case 1    
	const css_default = "/serviciolocal/ess/shared/css/ess1.css"
	const css_tablas = "/serviciolocal/ess/shared/css/tables3.css"
	const css_tablas_int = "/serviciolocal/ess/shared/css/tables_gray.css"
	const color_menu_off = "#F7C521"
	const color_menu_on = "#B99106"
	const color_sub_menu_off = "#003366"
	const color_sub_menu_on = "#336699"
' Case 2
'	const css_default = "/serviciolocal/ess/shared/css/default_2.css"
'	const css_tablas = "/serviciolocal/ess/shared/css/tables3_2.css"
'	const css_tablas_int = "css/tables_gray_2.css"
'	const color_menu_off = "#004000"
'	const color_menu_on = "#669966"
'	const color_sub_menu_off = "#669966"
'	const color_sub_menu_on = "Green"
' Case 3
'	const css_default = "/serviciolocal/ess/shared/css/default_3.css"
'	const css_tablas = "/serviciolocal/ess/shared/css/tables3_3.css"
'	const css_tablas_int = "/serviciolocal/ess/shared/css/tables_gray_3.css"
'	const color_menu_off = "#660000"
'	const color_menu_on = "#CC3300"
'	const color_sub_menu_off = "#CC3300"
'	const color_sub_menu_on = "Maroon"
%>

