<% 
const c_Estilo = "shared/css/ess.css" 'Estilo a usar
'const c_Estilo = "shared/css/ess_celeste.css" 'Estilo a usar
const c_EstiloTabla = "shared/css/tables_gray.css" 'Estilo a usar

'const c_x1 = "_@O"
'const c_x2 = "_@O"
const c_x1 = "5F404F"
const c_x2 = "5F404F"
const c_seed1 = "56238"     ' Usado como clave de encriptacion/desencriptacion
const c_MaxRecibos = 6      ' Indica la cantidad de recibos que se le muestran al empleado
const c_PassAutogestion = 1 'Indica si el password es Autogestionado: 0 = Falso - 1 = Verdadero
const c_TipoDocAg = 1       ' Indica el tipo de documento a buscar por el sistema de Autogestion, cuando se usa password autogestionado
'const c_SegIntegradaTipoDoc = 32 
const c_SegIntegradaTipoDoc = 0
                                ' Indica si e utiliza el usuario de Windows para ingresar a Autogestion 
								' y el Nro. acorde en la tabla tipodocu
const c_email_info = "info@rhpro.com.ar" ' Indica el mail a informar si se olvido la contraseña

%>