<% 
const cTimeout = 45 ' Minutos

' Configuración de Envió de Mails
const cEmailHost = "132.147.160.99" ' "<ip/nombre servidor de mail>"
const cEmailPort = 25 ' "<numero puerto SMTP servidor de mail>"
const cEmailUserid = "anonymous"
const cEmailFromAddress = "" ' "<direccion de email de Recursos Humanos>"
const cEmailFromName = "Eventos de Capacitacion" ' "Alertas de AutoGestion"
const cEmailReplyTo = "" '"<direccion de email de Recursos Humanos>"

const cEmailFromNamePost = "Agradecimiento C.V." ' "Agradecimiento de CV por e-mail"

const cDomain1 = "domdesabb" ' Nombre del 1er Dominio donde se vaidan los usuarios
const cDomain2 = "bbdesa2"     ' Nombre del 2do Dominio donde se vaidan los usuarios
%>