<% 
const cautoevaluador = 1
const cevaluador = 6   '2
const csupevaluador = 4
const cpotencial = 1

const cUsaMail= 0
const cEmailFromAddressEVA	= "claurossi@bvconline.com.ar"	' "<direccion de email de Recursos Humanos>"
const cEmailFromNameEVA		= "Evaluación de Desempeño" 
const cEmailReplyToEVA		= "claurossi@bvconline.com.ar"	'<direccion de email de Recursos Humanos>
const cEmailFromNamePostEVA	= "Evaluación de Desempeño" 

const cmismo_objetivo = 1 
'0: cada evaluador define sus propios objetivos
'1: Todos los evaluadoes del mismo empleados tienen el mismo objetivo.

const ctenro = 4 ' puesto para buscar observables en carga resultados

const cejemplo = 0 ' define si se pide el campo Ejemplos de Comportamientos Observados
				   ' en la seccion de carga de Competencias (-1: ABN!!!)

const careas = -1 ' define si las competencias se seleccionan para la MISMA area

const cseccalificacion = 2

const cformed = 0 ' si debe mostrar forma de medicion en defincion de objetivos smart

'DELOITTE
const cTenroRol = 51 ' indica el tenro del tipo de estructura de Roles de Evaluacion 
const cdepartamento   =  9 ' tenro del departamento
const cdeloitte = 1
%>